export default [
  {
    id: 1,
    title: "Waffle with Berries",
    type: "Waffle",
    price: 6.5,
    img: "assets/images/image-waffle-desktop.jpg",
    thumb: "assets/images/image-waffle-thumbnail.jpg",
  },
  {
    id: 2,
    title: "Vanilla Bean Crème Brûlée",
    type: "Crème Brûlée",
    price: 7.0,
    img: "assets/images/image-creme-brulee-desktop.jpg",
    thumb: "assets/images/image-creme-brulee-thumbnail.jpg",
  },
  {
    id: 3,
    title: "Mix of Five",
    type: "Macaron",
    price: 8.0,
    img: "assets/images/image-macaron-desktop.jpg",
    thumb: "assets/images/image-macaron-thumbnail.jpg",
  },
  {
    id: 4,
    title: "Classic Tiramisu",
    type: "Tiramisu",
    price: 5.5,
    img: "assets/images/image-tiramisu-desktop.jpg",
    thumb: "assets/images/image-tiramisu-thumbnail.jpg",
  },
  {
    id: 5,
    title: "Pistachio Baklava",
    type: "Baklava",
    price: 4.0,
    img: "assets/images/image-baklava-desktop.jpg",
    thumb: "assets/images/image-baklava-thumbnail.jpg",
  },
  {
    id: 6,
    title: "Lemon Meringue Pie",
    type: "Pie",
    price: 5.0,
    img: "assets/images/image-meringue-desktop.jpg",
    thumb: "assets/images/image-meringue-thumbnail.jpg",
  },
  {
    id: 7,
    title: "Red Velvet Cake",
    type: "Cake",
    price: 4.5,
    img: "assets/images/image-cake-desktop.jpg",
    thumb: "assets/images/image-cake-thumbnail.jpg",
  },
  {
    id: 8,
    title: "Salted Caramel Brownie",
    type: "Brownie",
    price: 4.5,
    img: "assets/images/image-brownie-desktop.jpg",
    thumb: "assets/images/image-brownie-thumbnail.jpg",
  },
  {
    id: 9,
    title: "Vanilla Panna Cotta",
    type: "Panna Cotta",
    price: 6.5,
    img: "assets/images/image-panna-cotta-desktop.jpg",
    thumb: "assets/images/image-panna-cotta-thumbnail.jpg",
  },
];
